## Basic Configuration
baseurl = "https://upbeat-mcclintock-05ba11.netlify.app/"
languageCode = "en"

title = "Ryan Safner"
theme = "hyde-hyde"

## Hugo Built-in Features
# disqusShortname = "your-disqus-shortname"
# googleAnalytics = "your-google-analytics-id"
# enableRobotsTXT = true

# summarylength = 30

#paginate = 5

## Site Settings
[params]
    author = "Ryan Safner"
    title = "Title"
    description = "Assistant Professor of Economics at Hood College"
    #authorimage = "/img/summer_2019.JPG"
    dateformat = "Jan 2, 2006"
    mainSections = "about"
    # themeColor = "theme-base-0d"
    # googleAnalytics = "Your tracking code"

    # sidebar, copyright & license
    #logoimage = "/img/hugo.png"
    copyright = "htr3n"
    since = 2019
    license = "CC BY-SA 4.0"
    licenseURL = "https://creativecommons.org/licenses/by-sa/4.0"
    showBuiltWith = true

    # https://highlightjs.org
    highlightjs = true
    highlightjsstyle = "github"
    
    # please choose either GraphComment or Disqus or Utterances
    #GraphCommentId = "..."
    #UtterancesRepo = "..." # https://utteranc.es/
    #UtterancesIssueTerm = "..." # pathname, url, title, og:title
    #UtterancesTheme = "..." # github-light or github-dark

    # Table of contents
    #toc = none, "hugo", or "tocbot"

## Social Accounts
[params.social]
    github = "ryansafner"
    #instagram = "ryansafner"
    #xing = "<username>"
    linkedin = "ryansafner"
    twitter = "ryansafner"
    facebook = "ryansafner"
    #microblog = "<username>"
    #stackoverflow = "<username>"
    #telegram = "<username>"
    orcid = "0000-0002-6177-9308"
    email = "safner@hood.edu"
    gravatar = "ryansafner@gmail.com"
    # pgpkey = "<path-to-your-key-in-/static>"

## Main Menu
[[menu.main]]
    name = "Teaching"
    weight = 50
    identifier = "posts"
    url = "/posts/"
[[menu.main]]
    name = "Posts"
    weight = 100
    identifier = "Teaching"
    url = "/Teaching/"
[[menu.main]]
    name = "Portfolio"
    identifier = "portfolio"
    weight = 200
    url = "/portfolio/"
[[menu.main]]
    name = "About"
    identifier = "about"
    weight = 300
    url = "/about/"
